#!/usr/bin/env python3
"""Generate the TLC configurations for the userns registry model."""
import pathlib

SAFETY = ["TypeOK", "LiveRangesDisjoint", "ManagedCoversLive", "ResourcesOfLiveKept",
          "RegistryConsistent", "NoStarvationByDead"]
LIVENESS = ["UnusedNamespaceDies", "RangeReclaimed"]

DEFAULTS = dict(Clients='{"c1", "c2"}', Role="RoleDef", Inodes="{1, 2}", Ranges='{"r1", "r2"}',
                IdMax=4, RingCap=4, RestartBudget=1,
                FDSTORE_PINS=False, FIX_NSID_VERIFY=True, FIX_REAP_ON_ALLOC=True,
                FIX_STARTUP_SWEEP=True, FIX_RINGBUF_LOCK=True)

# name: (overrides, invariants, properties, expectation, description)
CONFIGS = {
    "registry_fixed": ({}, SAFETY, LIVENESS, "pass",
                       "every fix on, the fd store does not pin (what runs), no ring buffer drop: every property"),
    "registry_fdstore_pins": (dict(FDSTORE_PINS=True), SAFETY, ["UnusedNamespaceDies"], "violation",
                       "the fd store pins the namespace as the source intends: UnusedNamespaceDies (a namespace no client references stays alive, its range is never returned)"),
    "registry_no_nsid": (dict(FIX_NSID_VERIFY=False), ["LiveRangesDisjoint", "ManagedCoversLive"], [], "violation",
                       "no NS_GET_ID in the registry (before 01e6465b55): a death event for a reused inode releases the new namespace's registration"),
    "registry_no_reap": (dict(FIX_REAP_ON_ALLOC=False, RingCap=1, RestartBudget=0, Inodes="{1, 2, 3}"), ["NoStarvationByDead"], [], "violation",
                       "no reclaim during allocation (before a77838a950), a dropped death event, an inode that is not reused: NoStarvationByDead (a dead namespace's range starves an allocation)"),
    "registry_fixed_3inodes": (dict(Inodes="{1, 2, 3}"), SAFETY, LIVENESS, "pass",
                       "every fix on with three inode numbers, so that dead entries are not always cleaned up through inode reuse"),
    "registry_ringbuf_drop": (dict(RingCap=1, RestartBudget=0), ["TypeOK"], ["RangeReclaimed"], "violation",
                       "a dropped death event, no restart: RangeReclaimed (nothing but the next allocation that runs out of ranges reclaims the entry)"),
    "registry_no_ringbuf_lock": (dict(FIX_RINGBUF_LOCK=False), SAFETY, LIVENESS, "pass",
                       "the manager releases without the registry lock: nothing the model checks depends on it (its registry updates are atomic)"),
}

def fmt(v):
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    return str(v)

here = pathlib.Path(__file__).resolve().parent
for old in here.glob("*.cfg"):
    if old.stem not in CONFIGS:
        old.unlink()
for name, (over, invs, props, expect, desc) in CONFIGS.items():
    c = dict(DEFAULTS, **over)
    lines = [f"\\* generated by gen-cfgs.py, expected: {expect}", f"\\* {desc}",
             "SPECIFICATION Spec", "CONSTANTS",
             f"  Clients = {c['Clients']}", f"  Role <- {c['Role']}",
             f"  Inodes = {c['Inodes']}", f"  Ranges = {c['Ranges']}"]
    for k in ["IdMax", "RingCap", "RestartBudget", "FDSTORE_PINS", "FIX_NSID_VERIFY",
              "FIX_REAP_ON_ALLOC", "FIX_STARTUP_SWEEP", "FIX_RINGBUF_LOCK"]:
        lines.append(f"  {k} = {fmt(c[k])}")
    if invs:
        lines.append("INVARIANTS")
        lines += [f"  {i}" for i in invs]
    if props:
        lines.append("PROPERTIES")
        lines += [f"  {p}" for p in props]
    (here / f"{name}.cfg").write_text("\n".join(lines) + "\n")
    print(name, expect)
