#!/usr/bin/env python3
"""Generate the TLC configurations for the verity sharing model."""
import pathlib

SAFETY = ["TypeOK", "OpenCountExact", "MountedIsActive", "NoOpenWhileDeleting"]
LIVENESS = ["EveryWorkerFinishes", "NoOrphanDevice"]

DEFAULTS = dict(Workers='{"w1", "w2"}', Attempts=2, WorkerMayDie=False, UDEV_SYNC=True,
                FIX_CANCEL_DEFERRED=True, FIX_RESTORE_DEFERRED=True)

# name: (overrides, invariants, properties, expectation, description)
CONFIGS = {
    "verity_fixed": ({}, SAFETY, LIVENESS, "pass",
                     "two workers, two attempts each: every property"),
    "verity_3workers": (dict(Workers='{"w1", "w2", "w3"}'), SAFETY, LIVENESS, "pass",
                     "three workers, two attempts each: every property"),
    "verity_no_cancel": (dict(FIX_CANCEL_DEFERRED=False), SAFETY, LIVENESS, "pass",
                     "no dm_deferred_remove_cancel() before reusing: the retries absorb the removals"),
    "verity_no_udev_sync": (dict(UDEV_SYNC=False), SAFETY, ["NoOrphanDevice"], "violation",
                     "activation returns before udev created the symlink: NoOrphanDevice (a worker that activated the device, could not open it and ran out of attempts leaves it without deferred removal, restore_deferred_remove is only set on the reuse path)"),
    "verity_no_restore": (dict(FIX_RESTORE_DEFERRED=False), SAFETY, ["NoOrphanDevice"], "violation",
                     "no re-arming of deferred removal when an attempt fails: NoOrphanDevice (a device whose removal a failed attempt cancelled stays behind)"),
    "verity_worker_dies": (dict(WorkerMayDie=True), SAFETY, ["NoOrphanDevice"], "violation",
                     "a worker killed between dm_deferred_remove_cancel() and its cleanup: NoOrphanDevice"),
}

def fmt(v):
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    return str(v)

here = pathlib.Path(__file__).resolve().parent
for old in here.glob("*.cfg"):
    if old.stem not in CONFIGS:
        old.unlink()
for name, (over, invs, props, expect, desc) in CONFIGS.items():
    c = dict(DEFAULTS, **over)
    lines = [f"\\* generated by gen-cfgs.py, expected: {expect}", f"\\* {desc}",
             "SPECIFICATION Spec", "CONSTANTS", f"  Workers = {c['Workers']}"]
    for k in ["Attempts", "WorkerMayDie", "UDEV_SYNC", "FIX_CANCEL_DEFERRED", "FIX_RESTORE_DEFERRED"]:
        lines.append(f"  {k} = {fmt(c[k])}")
    if invs:
        lines.append("INVARIANTS")
        lines += [f"  {i}" for i in invs]
    if props:
        lines.append("PROPERTIES")
        lines += [f"  {p}" for p in props]
    (here / f"{name}.cfg").write_text("\n".join(lines) + "\n")
    print(name, expect)
