#!/usr/bin/env python3
"""Generate the TLC configurations: one green config per thread layout
with every fix on, and one config per bug with its fix switched off."""
import pathlib

FIXES = ["FIX_RCU_RELEASE", "FIX_SIGPENDING_DUMPCORE", "FIX_RETARGET_GROUP_EXIT",
         "FIX_WORKER_NODUMP", "FIX_PTRACE_MASK", "FIX_EXEC_CANCEL_FIRST",
         "FIX_GATE_SIGNALED", "FIX_GATE_POSTCOREDUMP"]

SAFETY = ["TypeOK", "RemainingNonNegative", "CountConsistent",
          "OnlyCountedDecrement", "ReleasedAfterAllParked", "NoUseAfterFree",
          "SingleThreadedExec", "WorkerNeverDumps", "WorkerMaskIntact",
          "TruncationJustified", "FreezeAbortsDump"]
LIVENESS = ["KillTerminates", "DumpEnds"]

LAYOUTS = {
    # name: (module, leader, chunks, KILL, CORE, TERM, USR, exec, tracer, retry)
    "signals": ("MC_signals", "m", 2, 1, 1, 1, 1, 0, 0, 0),
    "sqpoll":  ("MC_sqpoll",  "m", 2, 1, 1, 0, 0, 0, 1, 0),
    "plain":   ("MC_plain",   "m", 2, 1, 1, 0, 1, 1, 0, 1),
    "cdhole":  ("MC_cdhole",  "m", 2, 1, 1, 0, 0, 0, 0, 0),
}

# name: (layout, fixes switched off, invariants, properties, expectation[, budget overrides])
CONFIGS = {
    "signals_fixed":         ("signals", [], SAFETY, LIVENESS, "pass"),
    "signals_no_rcu":        ("signals", ["FIX_RCU_RELEASE"], ["NoUseAfterFree"], [], "violation"),
    "signals_no_retarget":   ("signals", ["FIX_RETARGET_GROUP_EXIT", "FIX_SIGPENDING_DUMPCORE"], ["TruncationJustified"], [], "violation"),
    "signals_retarget_only": ("signals", ["FIX_RETARGET_GROUP_EXIT"], ["TruncationJustified"], [], "pass"),
    "signals_sigpending_only": ("signals", ["FIX_SIGPENDING_DUMPCORE"], ["TruncationJustified"], [], "pass"),
    "signals_no_freezer":    ("signals", ["FIX_SIGPENDING_DUMPCORE"], ["FreezeAbortsDump"], [], "violation"),
    "sqpoll_fixed":          ("sqpoll", [], SAFETY, LIVENESS, "pass"),
    "sqpoll_deadlock":       ("sqpoll", ["FIX_WORKER_NODUMP", "FIX_PTRACE_MASK"], ["TypeOK"], ["DumpEnds"], "violation"),
    "sqpoll_mask_only":      ("sqpoll", ["FIX_WORKER_NODUMP"], ["TypeOK"], ["DumpEnds"], "pass"),
    "sqpoll_no_gate_signaled": ("sqpoll", ["FIX_GATE_SIGNALED"], ["CountConsistent"], [], "violation"),
    "plain_fixed":           ("plain", [], SAFETY, [], "pass"),
    "plain_live":            ("plain", [], SAFETY, LIVENESS, "pass", {"usr": 0, "retry": 0}),
    "plain_strict":          ("plain", [], ["TruncationJustifiedStrict"], [], "violation"),
    "plain_no_exec_cancel":  ("plain", ["FIX_EXEC_CANCEL_FIRST"], ["SingleThreadedExec"], [], "violation"),
    "cdhole_fixed":          ("cdhole", [], SAFETY, LIVENESS, "pass"),
    "cdhole_no_gate":        ("cdhole", ["FIX_GATE_POSTCOREDUMP"], ["CountConsistent"], [], "violation"),
}

here = pathlib.Path(__file__).resolve().parent
for name, entry in CONFIGS.items():
    layout, off, invs, props, expect = entry[:5]
    over = entry[5] if len(entry) > 5 else {}
    module, leader, chunks, kill, core, term, usr, execb, tracer, retry = LAYOUTS[layout]
    usr = over.get("usr", usr); retry = over.get("retry", retry)
    lines = [f"\\* generated by gen-cfgs.py: layout {layout}, expected: {expect}",
             "SPECIFICATION Spec", "CONSTANTS",
             "  NoThread = NoThread",
             "  Threads <- ThreadsDef", "  Role <- RoleDef",
             "  Owner0 <- Owner0Def", "  RingOwners <- RingOwnersDef",
             f'  Leader = "{leader}"', f"  Chunks = {chunks}",
             f"  BudgetKILL = {kill}", f"  BudgetCORE = {core}",
             f"  BudgetTERM = {term}", f"  BudgetUSR = {usr}",
             f"  ExecBudget = {execb}", f"  TracerBudget = {tracer}",
             f"  RetryBudget = {retry}"]
    for f in FIXES:
        lines.append(f"  {f} = {'FALSE' if f in off else 'TRUE'}")
    if invs:
        lines.append("INVARIANTS")
        lines += [f"  {i}" for i in invs]
    if props:
        lines.append("PROPERTIES")
        lines += [f"  {p}" for p in props]
    (here / f"{name}.cfg").write_text("\n".join(lines) + "\n")
    print(name, "->", module)
