#!/bin/bash
# Run TLC on one configuration in the foreground: ./check.sh <config-name> [workers]
# Needs tla2tools.jar; point TLA2TOOLS at it.  TLC_OPTS passes extra options,
# TLC_HEAP the heap (default 4g), TLC_RECOVER=1 resumes from the newest checkpoint
# in the metadir.  A "\* tlc: <flags>" line in the .cfg adds per-configuration flags.
set -u
cd "$(dirname "$0")"
cfg=$1
workers=${2:-8}
jar=${TLA2TOOLS:-./tla2tools.jar}
module=MC_$cfg      # generated by gen-cfgs.py next to the .cfg, EXTENDS Fiber
meta=${TLC_METADIR:-/tmp/$USER-tlc-fiber}/$cfg
mkdir -p "$meta/tmp" logs
extra=$(sed -n 's/^\\\* tlc: //p' "$cfg.cfg" | head -1)
recover=
if [ "${TLC_RECOVER:-0}" = 1 ]; then
    chk=$(ls -d "$meta"/*/ 2>/dev/null | grep -E '/[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}/$' | sort | tail -1)
    [ -n "$chk" ] && recover="-recover ${chk%/}"
fi
java -XX:+UseParallelGC -Xmx${TLC_HEAP:-4g} -Djava.io.tmpdir="$meta/tmp" -cp "$jar" tlc2.TLC \
     -workers "$workers" -checkpoint 10 -metadir "$meta" $recover ${TLC_OPTS:-} $extra \
     -config "$cfg.cfg" "$module.tla" 2>&1 | tee "logs/$cfg.log" | \
     grep -E 'Error|violated|Finished|states generated|distinct|Invariant|Temporal|is not|Deadlock|Assertion|Attempted|TLC threw|stack trace|Exception|fails for|not enabled|line [0-9]+|Checkpointing'
echo "exit: ${PIPESTATUS[0]}  (full log: logs/$cfg.log)"
