---- MODULE MC_asis_stale_yield ----
\* generated by gen-cfgs.py, expected: violation
EXTENDS Fiber
MC_FiberOrder == <<"f1", "f2", "f3">>
MC_FiberPrioSeq == <<0, 0, 0>>
MC_ExtOrder == <<"x1", "x2">>
MC_WaitOrder == <<"w1", "w2", "w3">>
MC_TopLevel == {"f1"}
MC_FloatingTop == {}
MC_Ops == {"tobegin", "bare", "yield"}
====
