---- MODULE MC_fixed_all ----
\* generated by gen-cfgs.py, expected: pass
EXTENDS Fiber
MC_FiberOrder == <<"f1", "f2", "f3">>
MC_FiberPrioSeq == <<0, 0, 0>>
MC_ExtOrder == <<"x1", "x2">>
MC_WaitOrder == <<"w1", "w2", "w3">>
MC_TopLevel == {"f1", "f2"}
MC_FloatingTop == {}
MC_Ops == {"yield", "ext", "spawn", "spawnfl", "awaitf", "cancel", "exit", "tobegin", "toend", "bare"}
====
